Updated 41 cloud services (IPv4: 150027, IPv6: 278129)
INFO - Saved aws.csv [IPv4: 7800, IPv6: 3182]
INFO - Saved cloudflare.csv [IPv4: 62, IPv6: 53]
INFO - Saved google-cloud.csv [IPv4: 1126, IPv6: 110]
INFO - Saved bunny-cdn.csv [IPv4: 585, IPv6: 321]
INFO - Saved oracle-cloud.csv [IPv4: 1107, IPv6: 220]
INFO - Saved ahrefs.csv [IPv4: 10350, IPv6: 0]
INFO - Saved linode.csv [IPv4: 5409, IPv6: 96]
INFO - Saved vultr.csv [IPv4: 441, IPv6: 51]
INFO - Saved openai.csv [IPv4: 228, IPv6: 0]
INFO - Saved gcore-cdn.csv [IPv4: 356, IPv6: 0]
INFO - Saved apple-private-relay.csv [IPv4: 41981, IPv6: 245860]
INFO - Saved atlassian.csv [IPv4: 106, IPv6: 60]
INFO - Saved datadog.csv [IPv4: 146, IPv6: 2]
INFO - Saved okta.csv [IPv4: 2105, IPv6: 0]
INFO - Saved grafana-cloud.csv [IPv4: 562, IPv6: 0]
INFO - Saved intercom.csv [IPv4: 12, IPv6: 0]
INFO - Successfully loaded CycleTLS shared library: /home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/.venv/lib/python3.10/site-packages/cycletls/dist/libcycletls-linux-x64.so
INFO - Saved branch.csv [IPv4: 36, IPv6: 0]
INFO - Saved microsoft-azure.csv [IPv4: 48757, IPv6: 18688]
ERROR - Failed to fetch https://geofeed.equinixmetal.com/ for equinix_metal: 503 Server Error: Service Unavailable for url: https://geofeed.equinixmetal.com/
ERROR - Failed to fetch equinix_metal: Failed to fetch equinix_metal
ERROR - Failed to fetch equinix_metal
Traceback (most recent call last):
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/sources/http.py", line 17, in fetch_and_save_http_source
    r.raise_for_status()
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/.venv/lib/python3.10/site-packages/requests/models.py", line 1167, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://geofeed.equinixmetal.com/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/cloud_ip_ranges.py", line 725, in fetch_all
    if res := self._fetch_and_save(source):
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/cloud_ip_ranges.py", line 448, in _fetch_and_save
    transformed_data = fetch_and_save_http_source(self, source_key, url, headers=headers)
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/sources/http.py", line 28, in fetch_and_save_http_source
    raise RuntimeError(f"Failed to fetch {source_key}") from e
RuntimeError: Failed to fetch equinix_metal
INFO - Saved exoscale.csv [IPv4: 46, IPv6: 19]
INFO - Saved softlayer-ibm.csv [IPv4: 2909, IPv6: 3598]
INFO - Saved heroku-aws.csv [IPv4: 1410, IPv6: 633]
INFO - Saved a2hosting.csv [IPv4: 76, IPv6: 0]
INFO - Saved godaddy.csv [IPv4: 316, IPv6: 20]
INFO - Saved alibaba.csv [IPv4: 1191, IPv6: 149]
INFO - Saved tencent.csv [IPv4: 4408, IPv6: 296]
INFO - Saved ucloud.csv [IPv4: 744, IPv6: 12]
INFO - Saved meta-crawler.csv [IPv4: 346, IPv6: 427]
INFO - Saved huawei-cloud.csv [IPv4: 967, IPv6: 115]
INFO - Saved hetzner.csv [IPv4: 6121, IPv6: 578]
INFO - Saved choopa.csv [IPv4: 1740, IPv6: 1383]
INFO - Saved ovh.csv [IPv4: 2647, IPv6: 346]
INFO - Saved onlinesas.csv [IPv4: 20, IPv6: 8]
INFO - Saved rackspace.csv [IPv4: 678, IPv6: 154]
INFO - Saved nforce.csv [IPv4: 1185, IPv6: 458]
INFO - Saved upcloud.csv [IPv4: 88, IPv6: 20]
INFO - Saved aruba-cloud.csv [IPv4: 11, IPv6: 1]
INFO - Saved ionos-cloud.csv [IPv4: 522, IPv6: 20]
INFO - Saved cyso-cloud.csv [IPv4: 15, IPv6: 4]
INFO - Saved seeweb.csv [IPv4: 36, IPv6: 10]
INFO - Saved wasabi.csv [IPv4: 20, IPv6: 0]
INFO - Saved kamatera.csv [IPv4: 140, IPv6: 19]