Updated 42 cloud services (IPv4: 150355, IPv6: 278336)
INFO - Saved aws.json [IPv4: 7792, IPv6: 3421]
INFO - Saved cloudflare.json [IPv4: 61, IPv6: 51]
INFO - Saved google-cloud.json [IPv4: 1131, IPv6: 110]
INFO - Saved bunny-cdn.json [IPv4: 585, IPv6: 322]
INFO - Saved oracle-cloud.json [IPv4: 1107, IPv6: 220]
INFO - Saved ahrefs.json [IPv4: 10350, IPv6: 0]
INFO - Saved linode.json [IPv4: 5409, IPv6: 96]
INFO - Saved vultr.json [IPv4: 441, IPv6: 51]
INFO - Saved openai.json [IPv4: 234, IPv6: 0]
INFO - Saved gcore-cdn.json [IPv4: 358, IPv6: 0]
INFO - Saved apple-private-relay.json [IPv4: 41981, IPv6: 245860]
INFO - Saved atlassian.json [IPv4: 106, IPv6: 60]
INFO - Saved datadog.json [IPv4: 146, IPv6: 2]
INFO - Saved okta.json [IPv4: 2112, IPv6: 0]
INFO - Saved grafana-cloud.json [IPv4: 561, IPv6: 0]
INFO - Saved intercom.json [IPv4: 12, IPv6: 0]
INFO - Successfully loaded CycleTLS shared library: /home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/.venv/lib/python3.10/site-packages/cycletls/dist/libcycletls-linux-x64.so
INFO - Saved branch.json [IPv4: 36, IPv6: 0]
INFO - Saved microsoft-azure.json [IPv4: 48785, IPv6: 18677]
INFO - Saved equinix-metal.json [IPv4: 172, IPv6: 61]
INFO - Saved exoscale.json [IPv4: 46, IPv6: 19]
INFO - Saved softlayer-ibm.json [IPv4: 2917, IPv6: 3612]
INFO - Saved heroku-aws.json [IPv4: 1428, IPv6: 635]
INFO - Saved a2hosting.json [IPv4: 76, IPv6: 0]
INFO - Saved godaddy.json [IPv4: 310, IPv6: 20]
INFO - Saved alibaba.json [IPv4: 1189, IPv6: 148]
INFO - Saved tencent.json [IPv4: 4411, IPv6: 298]
INFO - Saved ucloud.json [IPv4: 744, IPv6: 12]
INFO - Saved meta-crawler.json [IPv4: 345, IPv6: 424]
INFO - Saved huawei-cloud.json [IPv4: 972, IPv6: 115]
INFO - Saved hetzner.json [IPv4: 6157, IPv6: 579]
INFO - Saved choopa.json [IPv4: 1742, IPv6: 1256]
INFO - Saved ovh.json [IPv4: 2732, IPv6: 382]
INFO - Saved onlinesas.json [IPv4: 20, IPv6: 8]
INFO - Saved rackspace.json [IPv4: 679, IPv6: 154]
INFO - Saved nforce.json [IPv4: 1188, IPv6: 459]
INFO - Saved upcloud.json [IPv4: 87, IPv6: 20]
INFO - Saved aruba-cloud.json [IPv4: 11, IPv6: 1]
INFO - Saved ionos-cloud.json [IPv4: 522, IPv6: 20]
INFO - Saved cyso-cloud.json [IPv4: 15, IPv6: 4]
INFO - Saved seeweb.json [IPv4: 36, IPv6: 10]
INFO - Saved wasabi.json [IPv4: 20, IPv6: 0]
INFO - Saved kamatera.json [IPv4: 140, IPv6: 19]
ERROR - Failed to fetch https://yandex.cloud/en/docs/security/ip-list for yandex_cloud: 403 Client Error: Forbidden for url: https://yandex.cloud/en/docs/security/ip-list
ERROR - Failed to fetch yandex_cloud: Failed to fetch yandex_cloud
ERROR - Failed to fetch yandex_cloud
Traceback (most recent call last):
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/sources/http.py", line 17, in fetch_and_save_http_source
    r.raise_for_status()
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/.venv/lib/python3.10/site-packages/requests/models.py", line 1167, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://yandex.cloud/en/docs/security/ip-list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/cloud_ip_ranges.py", line 725, in fetch_all
    if res := self._fetch_and_save(source):
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/cloud_ip_ranges.py", line 448, in _fetch_and_save
    transformed_data = fetch_and_save_http_source(self, source_key, url, headers=headers)
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/sources/http.py", line 28, in fetch_and_save_http_source
    raise RuntimeError(f"Failed to fetch {source_key}") from e
RuntimeError: Failed to fetch yandex_cloud