Updated 43 cloud services (IPv4: 150214, IPv6: 278448)
INFO - Saved aws.txt [IPv4: 7807, IPv6: 3417]
INFO - Saved cloudflare.txt [IPv4: 62, IPv6: 53]
INFO - Saved digitalocean.txt [IPv4: 1081, IPv6: 148]
INFO - Saved google-cloud.txt [IPv4: 1130, IPv6: 110]
INFO - Saved google-bot.txt [IPv4: 835, IPv6: 812]
INFO - Saved bunny-cdn.txt [IPv4: 586, IPv6: 322]
INFO - Saved oracle-cloud.txt [IPv4: 1107, IPv6: 220]
INFO - Saved ahrefs.txt [IPv4: 10350, IPv6: 0]
INFO - Saved linode.txt [IPv4: 5409, IPv6: 96]
INFO - Saved vultr.txt [IPv4: 441, IPv6: 51]
INFO - Saved openai.txt [IPv4: 229, IPv6: 0]
INFO - Saved gcore-cdn.txt [IPv4: 357, IPv6: 0]
INFO - Saved apple-private-relay.txt [IPv4: 41981, IPv6: 245860]
INFO - Saved atlassian.txt [IPv4: 106, IPv6: 60]
INFO - Saved datadog.txt [IPv4: 146, IPv6: 2]
INFO - Saved okta.txt [IPv4: 2118, IPv6: 0]
INFO - Saved grafana-cloud.txt [IPv4: 561, IPv6: 0]
INFO - Saved intercom.txt [IPv4: 12, IPv6: 0]
INFO - Successfully loaded CycleTLS shared library: /home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/.venv/lib/python3.10/site-packages/cycletls/dist/libcycletls-linux-x64.so
INFO - Saved branch.txt [IPv4: 36, IPv6: 0]
INFO - Saved microsoft-azure.txt [IPv4: 48785, IPv6: 18677]
ERROR - Failed to fetch https://geofeed.equinixmetal.com/ for equinix_metal: 503 Server Error: Service Unavailable for url: https://geofeed.equinixmetal.com/
ERROR - Failed to fetch equinix_metal: Failed to fetch equinix_metal
ERROR - Failed to fetch equinix_metal
Traceback (most recent call last):
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/sources/http.py", line 17, in fetch_and_save_http_source
    r.raise_for_status()
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/.venv/lib/python3.10/site-packages/requests/models.py", line 1167, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://geofeed.equinixmetal.com/

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/cloud_ip_ranges.py", line 725, in fetch_all
    if res := self._fetch_and_save(source):
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/cloud_ip_ranges.py", line 448, in _fetch_and_save
    transformed_data = fetch_and_save_http_source(self, source_key, url, headers=headers)
  File "/home/runner/work/cloud-ip-ranges/cloud-ip-ranges/crawler/src/sources/http.py", line 28, in fetch_and_save_http_source
    raise RuntimeError(f"Failed to fetch {source_key}") from e
RuntimeError: Failed to fetch equinix_metal
INFO - Saved exoscale.txt [IPv4: 46, IPv6: 19]
INFO - Saved softlayer-ibm.txt [IPv4: 2913, IPv6: 3604]
INFO - Saved heroku-aws.txt [IPv4: 1414, IPv6: 634]
INFO - Saved a2hosting.txt [IPv4: 76, IPv6: 0]
INFO - Saved godaddy.txt [IPv4: 311, IPv6: 20]
INFO - Saved alibaba.txt [IPv4: 1193, IPv6: 149]
INFO - Saved tencent.txt [IPv4: 4413, IPv6: 298]
INFO - Saved ucloud.txt [IPv4: 744, IPv6: 12]
INFO - Saved meta-crawler.txt [IPv4: 345, IPv6: 424]
INFO - Saved huawei-cloud.txt [IPv4: 969, IPv6: 115]
INFO - Saved hetzner.txt [IPv4: 6157, IPv6: 579]
INFO - Saved choopa.txt [IPv4: 1739, IPv6: 1447]
INFO - Saved ovh.txt [IPv4: 2732, IPv6: 368]
INFO - Saved onlinesas.txt [IPv4: 20, IPv6: 8]
INFO - Saved rackspace.txt [IPv4: 678, IPv6: 154]
INFO - Saved nforce.txt [IPv4: 1186, IPv6: 459]
INFO - Saved upcloud.txt [IPv4: 88, IPv6: 20]
INFO - Saved aruba-cloud.txt [IPv4: 11, IPv6: 1]
INFO - Saved ionos-cloud.txt [IPv4: 522, IPv6: 20]
INFO - Saved cyso-cloud.txt [IPv4: 15, IPv6: 4]
INFO - Saved seeweb.txt [IPv4: 36, IPv6: 10]
INFO - Saved wasabi.txt [IPv4: 20, IPv6: 0]
INFO - Saved kamatera.txt [IPv4: 140, IPv6: 19]